---
title: "Model Selection Practice - NV Gilas"
author: "C.S. Stratton"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 3
  base_font:
        google: "Arial"
---
<style type="text/css">

body{ /* Normal  */
      font-size: 16px;
      text-align: justified;
}


h1 { /* Header 1 */
  font-size: 42px;
  color: darkblue;
  text-decoration: underline;
  }

h2 { /* Header 2 */
  font-size: 30px;
  color: orangered;
  }


h3 { /* Header 2 */
  font-size: 24px;
  color: Black;
  }
  
</style>
---

```{r setup, include=FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(ggplot2)
library(arm)
library(ggfortify)
library(performance)
library(AICcmodavg)
library(grid)
library(hms)
library(scales)
library(lme4)
library(lmerTest)
library(MuMIn)
library(asbio)
library(GGally)
library(performance)
library(patchwork)
library(olsrr)

data_gila <- read.csv("data_gmocc-all-nv.csv")

#average of the shrub distance per point in cm
data_gila <- data_gila %>% mutate(avg_shr_dist = (shr_nw + shr_ne + shr_se + shr_sw) / 4)
#density of the shrubs in "shrubs/m^2"
data_gila <- data_gila %>% mutate(abs_shr_dens = (1/((avg_shr_dist/100))^2))

# making time graphable
data_gila$time <- paste0(data_gila$time, ":00") #adds 'seconds' to the data to put it in "%H:%M:%S" format
gila_time_posix <- strptime(data_gila$time, format = "%H:%M:%S") #Makes the "time" column character data a "POSIXlt" object
gila_time_hms <- as_hms(gila_time_posix) #Makes the Posix object an hms (hours, minutes, seconds) class object
data_gila$time_hms <- gila_time_hms # Brings the hms object back into the dataframe as a new column named "time_hms"

datatrim_gila <- dplyr::select(data_gila, c(site_id, tran_id, col_point, date, elev, avg_wind_spd, air_temp, rel_hum, gr_temp, rock_ind, abs_shr_dens, time_hms, det_strict, det_type_strict))
#Split between the sites
data_calico <- datatrim_gila %>% filter(site_id=="Calico Basin")
data_vof <- datatrim_gila %>% filter(site_id=="Valley of Fire")

knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```



```{r model anova}
#binomial model
model_calico <- glm(det_strict ~ elev + avg_wind_spd + air_temp + rel_hum + gr_temp + rock_ind + abs_shr_dens, data=data_calico, family=binomial(link="logit"))
#compare in anova for all coefficients
anova(model_calico)
```

```{r ggpairs}
#Graph the variables against each other
ggpairs(data_calico, columns = 5:11, cardinality_threshold = 15) + theme_bw()
```

```{r olsrr}
#added variable plots to see if any predictor fits when accounting for the others
olsrr::ols_plot_added_variable(model_calico)
```

```{r VIF}
#Using VIF to check collinearity
performance::check_collinearity(model_calico)
```

```{r binned residual plot}
#check model binned residual plot
x <- predict(model_calico)
y <- resid(model_calico)
binnedplot(x, y)
```

```{r Dredging <5}
#dredging!
options(na.action = "na.fail") # otherwise blows up with NA values
dredge_calico <- dredge(model_calico)
subset(dredge_calico, delta <5)
```

```{r Dredging <2}
subset(dredge_calico, delta <2)
```

```{r variable weights}
#variable weights
sw(dredge_calico)
```

```{r overall model summary <2}
#model summary
summary(model.avg(dredge_calico, subset = delta < 2))
```

```{r modeling coefficients}
#modeling coefficients averaged across all models

c1 <- ggplot(data_calico, aes(abs_shr_dens, det_strict)) + 
  geom_point() +
  geom_smooth(method="glm", method.args=list(family="binomial"(link="logit")))

c2 <- ggplot(data_calico, aes(avg_wind_spd, det_strict)) + 
  geom_point() +
  geom_smooth(method="glm", method.args=list(family="binomial"(link="logit")))

c3 <- ggplot(data_calico, aes(elev, det_strict)) + 
  geom_point() +
  geom_smooth(method="glm", method.args=list(family="binomial"(link="logit")))

c4 <- ggplot(data_calico, aes(gr_temp, det_strict)) + 
  geom_point() +
  geom_smooth(method="glm", method.args=list(family="binomial"(link="logit")))

c5 <- ggplot(data_calico, aes(rock_ind, det_strict)) + 
  geom_point() +
  geom_smooth(method="glm", method.args=list(family="binomial"(link="logit")))

c6 <- ggplot(data_calico, aes(air_temp, det_strict)) + 
  geom_point() +
  geom_smooth(method="glm", method.args=list(family="binomial"(link="logit")))

c7 <- ggplot(data_calico, aes(rel_hum, det_strict)) + 
  geom_point() +
  geom_smooth(method="glm", method.args=list(family="binomial"(link="logit")))

(c1 + c2) / (c3 + c4) / (c5 + c6) / (c7 + c7) #patchwork notation for figure alignment

```

